name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.10.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          scp -r ./build/* maksio@192.168.64.5:/var/www/html
